AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockLength:
  Max: 50

Layout/LineLength:
  Max: 120

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SignalException:
  EnforcedStyle: only_raise

Naming/MethodParameterName:
  MinNameLength: 2

Style/NumericPredicate:
  EnforcedStyle: predicate

Bundler/OrderedGems:
  Enabled: false
